title: CU_scout_nav_docs
description: Documentation for working with the Scout and Nav2 at Clarkson University
theme: just-the-docs

url: https://arcater.github.io/CU_scout_nav_docs

nav_enabled: true

aux_links:
  CU_scout_nav_docs Repository: https://github.com/arcater/CU_scout_nav_docs
